import '../../model/sfemodel/sfe_choice_mode.dart';

List<SFEChoiceModel> choicesList = [
  SFEChoiceModel(choiceId: 1, choiceCode: 'SA', choiceDesc: 'Strongly Agree', choiceNum: 1, choicePosVal: 1.00, choiceNegVal: 4.00),
  SFEChoiceModel(choiceId: 2, choiceCode: 'A', choiceDesc: 'Agree', choiceNum: 2, choicePosVal: 2.00, choiceNegVal: 3.00),
  SFEChoiceModel(choiceId: 3, choiceCode: 'D', choiceDesc: 'Disagree', choiceNum: 3, choicePosVal: 3.00, choiceNegVal: 2.00),
  SFEChoiceModel(choiceId: 4, choiceCode: 'SD', choiceDesc: 'Strongly Disagree', choiceNum: 4, choicePosVal: 4.00, choiceNegVal: 1.00),
  SFEChoiceModel(choiceId: 5, choiceCode: 'NA', choiceDesc: 'Not Applicable', choiceNum: 5, choicePosVal: 0.00, choiceNegVal: 0.00),
  SFEChoiceModel(choiceId: 6, choiceCode: '0', choiceDesc: '0 time', choiceNum: 1, choicePosVal: 1.00, choiceNegVal: 5.00),
  SFEChoiceModel(choiceId: 7, choiceCode: '1', choiceDesc: '1 time', choiceNum: 2, choicePosVal: 2.00, choiceNegVal: 4.00),
  SFEChoiceModel(choiceId: 8, choiceCode: '2-3', choiceDesc: '2-3 times', choiceNum: 3, choicePosVal: 3.00, choiceNegVal: 3.00),
  SFEChoiceModel(choiceId: 9, choiceCode: '4-5', choiceDesc: '4-5 times', choiceNum: 4, choicePosVal: 4.00, choiceNegVal: 2.00),
  SFEChoiceModel(choiceId: 10, choiceCode: '6', choiceDesc: '6 times', choiceNum: 5, choicePosVal: 5.00, choiceNegVal: 1.00),
  SFEChoiceModel(choiceId: 11, choiceCode: 'NA', choiceDesc: 'Not Applicable', choiceNum: 6, choicePosVal: 0.00, choiceNegVal: 0.00),
  SFEChoiceModel(choiceId: 12, choiceCode: 'TE', choiceDesc: 'Too Early', choiceNum: 1, choicePosVal: 0.00, choiceNegVal: 0.00),
  SFEChoiceModel(choiceId: 13, choiceCode: 'OT', choiceDesc: 'On Time', choiceNum: 2, choicePosVal: 0.00, choiceNegVal: 0.00),
  SFEChoiceModel(choiceId: 14, choiceCode: 'L', choiceDesc: 'Late', choiceNum: 3, choicePosVal: 0.00, choiceNegVal: 0.00),
  SFEChoiceModel(choiceId: 15, choiceCode: 'VL', choiceDesc: 'Very Late', choiceNum: 4, choicePosVal: 0.00, choiceNegVal: 0.00),
  SFEChoiceModel(choiceId: 16, choiceCode: 'NA', choiceDesc: 'Not Applicable', choiceNum: 5, choicePosVal: 0.00, choiceNegVal: 0.00),
  SFEChoiceModel(choiceId: 17, choiceCode: 'Y', choiceDesc: 'Yes', choiceNum: 1, choicePosVal: 0.00, choiceNegVal: 0.00),
  SFEChoiceModel(choiceId: 18, choiceCode: 'N', choiceDesc: 'No', choiceNum: 2, choicePosVal: 0.00, choiceNegVal: 0.00),
  SFEChoiceModel(choiceId: 19, choiceCode: '1W', choiceDesc: '1 week', choiceNum: 1, choicePosVal: 0.00, choiceNegVal: 0.00),
  SFEChoiceModel(choiceId: 20, choiceCode: '2WS', choiceDesc: '2 weeks', choiceNum: 2, choicePosVal: 0.00, choiceNegVal: 0.00),
  SFEChoiceModel(choiceId: 21, choiceCode: '1M', choiceDesc: '1 month', choiceNum: 3, choicePosVal: 0.00, choiceNegVal: 0.00),
  SFEChoiceModel(choiceId: 22, choiceCode: '>1M', choiceDesc: 'More than 1 month', choiceNum: 4, choicePosVal: 0.00, choiceNegVal: 0.00),
  SFEChoiceModel(choiceId: 23, choiceCode: 'N', choiceDesc: 'Never', choiceNum: 5, choicePosVal: 0.00, choiceNegVal: 0.00),
  SFEChoiceModel(choiceId: 25, choiceCode: 'A', choiceDesc: 'Always', choiceNum: 1, choicePosVal: 0.00, choiceNegVal: 0.00),
  SFEChoiceModel(choiceId: 26, choiceCode: 'U', choiceDesc: 'Usually', choiceNum: 2, choicePosVal: 0.00, choiceNegVal: 0.00),
  SFEChoiceModel(choiceId: 27, choiceCode: 'S', choiceDesc: 'Sometimes', choiceNum: 3, choicePosVal: 0.00, choiceNegVal: 0.00),
  SFEChoiceModel(choiceId: 28, choiceCode: 'R', choiceDesc: 'Rarely', choiceNum: 4, choicePosVal: 0.00, choiceNegVal: 0.00),
  SFEChoiceModel(choiceId: 29, choiceCode: 'N', choiceDesc: 'Never', choiceNum: 5, choicePosVal: 0.00, choiceNegVal: 0.00),
  SFEChoiceModel(choiceId: 30, choiceCode: 'NA', choiceDesc: 'Not Applicable', choiceNum: 6, choicePosVal: 0.00, choiceNegVal: 0.00),
  SFEChoiceModel(choiceId: 31, choiceCode: 'TB', choiceDesc: 'The best', choiceNum: 1, choicePosVal: 0.00, choiceNegVal: 0.00),
  SFEChoiceModel(choiceId: 32, choiceCode: 'AB', choiceDesc: 'Among the best', choiceNum: 2, choicePosVal: 0.00, choiceNegVal: 0.00),
  SFEChoiceModel(choiceId: 33, choiceCode: 'A', choiceDesc: 'Average', choiceNum: 3, choicePosVal: 0.00, choiceNegVal: 0.00),
  SFEChoiceModel(choiceId: 34, choiceCode: 'AW', choiceDesc: 'Among the worst', choiceNum: 4, choicePosVal: 0.00, choiceNegVal: 0.00),
  SFEChoiceModel(choiceId: 35, choiceCode: 'TW', choiceDesc: 'The worst', choiceNum: 5, choicePosVal: 0.00, choiceNegVal: 0.00),
  SFEChoiceModel(choiceId: 36, choiceCode: 'NA', choiceDesc: 'Not Applicable', choiceNum: 6, choicePosVal: 0.00, choiceNegVal: 0.00),
  SFEChoiceModel(choiceId: 37, choiceCode: 'TF', choiceDesc: 'Too Fast', choiceNum: 1, choicePosVal: 0.00, choiceNegVal: 0.00),
  SFEChoiceModel(choiceId: 38, choiceCode: 'F', choiceDesc: 'Fast', choiceNum: 2, choicePosVal: 0.00, choiceNegVal: 0.00),
  SFEChoiceModel(choiceId: 39, choiceCode: 'JR', choiceDesc: 'Just Right', choiceNum: 3, choicePosVal: 0.00, choiceNegVal: 0.00),
  SFEChoiceModel(choiceId: 40, choiceCode: 'S', choiceDesc: 'Slow', choiceNum: 4, choicePosVal: 0.00, choiceNegVal: 0.00),
  SFEChoiceModel(choiceId: 41, choiceCode: 'TS', choiceDesc: 'Too Slow', choiceNum: 5, choicePosVal: 0.00, choiceNegVal: 0.00),
  SFEChoiceModel(choiceId: 42, choiceCode: 'VM', choiceDesc: 'Very Much', choiceNum: 1, choicePosVal: 1.00, choiceNegVal: 5.00),
  SFEChoiceModel(choiceId: 43, choiceCode: 'M', choiceDesc: 'Much', choiceNum: 2, choicePosVal: 2.00, choiceNegVal: 4.00),
  SFEChoiceModel(choiceId: 44, choiceCode: 'MS', choiceDesc: 'Moderately/Some', choiceNum: 3, choicePosVal: 3.00, choiceNegVal: 3.00),
  SFEChoiceModel(choiceId: 45, choiceCode: 'VL', choiceDesc: 'Very Little', choiceNum: 4, choicePosVal: 4.00, choiceNegVal: 2.00),
  SFEChoiceModel(choiceId: 46, choiceCode: 'N', choiceDesc: 'Nothing/Not at all', choiceNum: 5, choicePosVal: 5.00, choiceNegVal: 1.00),
  SFEChoiceModel(choiceId: 49, choiceCode: 'NA', choiceDesc: 'Not Applicable', choiceNum: 6, choicePosVal: 0.00, choiceNegVal: 0.00),
  SFEChoiceModel(choiceId: 50, choiceCode: '1.00', choiceDesc: '1.00', choiceNum: 1, choicePosVal: 1.00, choiceNegVal: 0),
  SFEChoiceModel(choiceId: 51, choiceCode: '1.25', choiceDesc: '1.25', choiceNum: 2, choicePosVal: 1.25, choiceNegVal: 0),
  SFEChoiceModel(choiceId: 52, choiceCode: '1.50', choiceDesc: '1.50', choiceNum: 3, choicePosVal: 1.50, choiceNegVal: 0),
  SFEChoiceModel(choiceId: 53, choiceCode: '1.75', choiceDesc: '1.75', choiceNum: 4, choicePosVal: 1.75, choiceNegVal: 0),
  SFEChoiceModel(choiceId: 54, choiceCode: '2.00', choiceDesc: '2.00', choiceNum: 5, choicePosVal: 2.00, choiceNegVal: 0),
  SFEChoiceModel(choiceId: 55, choiceCode: '2.25', choiceDesc: '2.25', choiceNum: 6, choicePosVal: 2.25, choiceNegVal: 0),
  SFEChoiceModel(choiceId: 56, choiceCode: '2.50', choiceDesc: '2.50', choiceNum: 7, choicePosVal: 2.50, choiceNegVal: 0),
  SFEChoiceModel(choiceId: 57, choiceCode: '2.75', choiceDesc: '2.75', choiceNum: 8, choicePosVal: 2.75, choiceNegVal: 0),
  SFEChoiceModel(choiceId: 58, choiceCode: '3.00', choiceDesc: '3.00', choiceNum: 9, choicePosVal: 3.00, choiceNegVal: 0),
  SFEChoiceModel(choiceId: 59, choiceCode: '5.00', choiceDesc: '5.00', choiceNum: 10, choicePosVal: 5.00, choiceNegVal: 0),
  SFEChoiceModel(choiceId: 60, choiceCode: 'INC', choiceDesc: 'Incomplete', choiceNum: 11, choicePosVal: 0.00, choiceNegVal: 0),
  SFEChoiceModel(choiceId: 61, choiceCode: 'NA', choiceDesc: 'Not Applicable', choiceNum: 12, choicePosVal: 0.00, choiceNegVal: 0),
  SFEChoiceModel(choiceId: 61, choiceCode: 'TF', choiceDesc: '', choiceNum: 1, choicePosVal: 0.00, choiceNegVal: 0),
  SFEChoiceModel(choiceId: 62, choiceCode: 'NA', choiceDesc: 'Not Applicable', choiceNum: 5, choicePosVal: 0.00, choiceNegVal: 0.00),
];